(defun SBS-PANEL-DIA (/ DIA-ID DIA_State)
(print "start panel dia")
	(setq DIA_ID (load_dialog "SBS-Dialog.dcl"))
	(IF (NOT (new_dialog "SBS_PanelProperties" DIA_ID))
		(EXIT)
	)
	(setq DIA_State (start_dialog))
	(unload_dialog DIA_ID)
)